# Surcharges pour l'environnement de développement (namespace devhub-dev).
# Ne mettez ICI que ce qui diffère de values.yaml.

image:
  tag: "0.1.1"

ingress:
  enabled: true
  host: annuaire.devhub.local

env:
  LOG_LEVEL: warn

failRate: "1"

# En étape 4 vous activerez le ServiceMonitor :
monitoring:
  enabled: true

# Étape 5 : Activer le Rollout (désactiver le Deployment de secours)
useDeployment: false
